# Generated by Django 4.2 on 2026-02-28 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('register_id', models.CharField(max_length=14, unique=True)),
                ('username', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('STUDENT', 'Student'), ('ALUMNI', 'Alumni')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='alumni_profile', serialize=False, to='user.user')),
                ('employment_status', models.CharField(choices=[('Employed', 'Employed'), ('Unemployed', 'Unemployed'), ('Higher Studies', 'Higher Studies')], max_length=20)),
                ('company_name', models.CharField(blank=True, max_length=150, null=True)),
                ('job_title', models.CharField(blank=True, max_length=100, null=True)),
                ('experience_year', models.IntegerField(blank=True, null=True)),
                ('pursuing_degree', models.CharField(blank=True, max_length=150, null=True)),
                ('university', models.CharField(blank=True, max_length=150, null=True)),
                ('available_for_referral', models.BooleanField(blank=True, default=False)),
            ],
            options={
                'db_table': 'alumni',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='student_profile', serialize=False, to='user.user')),
                ('bio', models.CharField(blank=True, max_length=250, null=True)),
                ('department', models.CharField(max_length=50)),
                ('admission_year', models.IntegerField()),
                ('graduation_year', models.IntegerField(blank=True, null=True)),
                ('phone', models.CharField(max_length=15)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('dob', models.DateField()),
                ('city', models.CharField(blank=True, max_length=20)),
                ('permanent_address', models.TextField()),
                ('photo', models.FileField(blank=True, null=True, upload_to='student_photos/')),
                ('resume', models.FileField(blank=True, null=True, upload_to='student_resumes/')),
                ('github_url', models.URLField(blank=True, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'db_table': 'student',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=200)),
                ('salary', models.CharField(blank=True, max_length=100, null=True)),
                ('last_date', models.DateField()),
                ('required_skills', models.TextField(default=True)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Open', max_length=20)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_jobs', to='user.user')),
            ],
            options={
                'db_table': 'Jobs',
            },
        ),
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=200)),
                ('stipend', models.CharField(blank=True, max_length=100, null=True)),
                ('last_date', models.DateField()),
                ('required_skills', models.TextField(default=True)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('duration', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(default='Open', max_length=20)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_internships', to='user.user')),
            ],
            options={
                'db_table': 'Internships',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('event_time', models.TimeField()),
                ('event_type', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Upcoming', max_length=20)),
                ('organized_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_events', to='user.user')),
            ],
            options={
                'db_table': 'Events',
            },
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('donated_at', models.DateTimeField(auto_now_add=True)),
                ('payment_method', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('donated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='user.user')),
            ],
            options={
                'db_table': 'donations',
            },
        ),
    ]
