# Generated by Django 4.2 on 2026-02-26 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='alumni_profile', serialize=False, to='user.user')),
                ('employment_status', models.CharField(choices=[('Employed', 'Employed'), ('Unemployed', 'Unemployed'), ('Higher Studies', 'Higher Studies')], max_length=20)),
                ('company_name', models.CharField(blank=True, max_length=150)),
                ('job_title', models.CharField(blank=True, max_length=100)),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('experience_year', models.IntegerField(blank=True, null=True)),
                ('pursuing_degree', models.CharField(blank=True, max_length=150)),
                ('university', models.CharField(blank=True, max_length=150)),
                ('willing_to_mentor', models.BooleanField(default=False)),
                ('available_for_referral', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'alumni',
            },
        ),
        migrations.AddField(
            model_name='student',
            name='bio',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='city',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(max_length=50),
        ),
    ]
