# Generated by Django 4.2 on 2026-02-28 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumni',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='alumni',
            name='willing_to_mentor',
        ),
        migrations.AlterField(
            model_name='alumni',
            name='available_for_referral',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='company_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='job_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='pursuing_degree',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='university',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
