# Generated by Django 4.2 on 2026-03-26 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_alumni_employment_status_alter_student_dob_and_more'),
        ('user', '0002_alter_alumni_employment_status_alter_student_gender_and_more'),
    ]

    operations = [
    ]
