# Generated by Django 4.2 on 2026-03-29 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_department_delete_college'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internship',
            name='status',
        ),
    ]
