# Generated by Django 4.2 on 2026-03-02 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_event_event_type_remove_event_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(default='General', max_length=100),
        ),
    ]
