# Generated by Django 6.0.3 on 2026-04-05 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_student_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship',
            name='required_skills',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='job',
            name='required_skills',
            field=models.TextField(default=''),
        ),
    ]
