from django.urls import path
from . import views

app_name = "user"

urlpatterns = [
    path("", views.home, name="home"),
    path("logout/", views.logout, name="logout"),
    path("admin_home/", views.home, name="admin_home"),
    path("alumni_home/", views.home, name="alumni_home"),
    path("user_home/", views.home, name="user_home"),
    path("events/view/", views.vi_event, name="vi_event"),
    path("events/create/", views.create_event, name="event_create"),
    path('delete-event/<int:event_id>/', views.delete_event, name='delete_event'),
    path('edit-event/<int:event_id>/', views.edit_event, name='edit_event'),
    path("achievements/view/", views.view_achievements, name = "achievements_view"),
    path("achievements/create/", views.create_achievements, name = "create_achievement"),
    path('achievements/edit/<int:achievement_id>/', views.edit_achievement, name='edit_achievement'),
    path('achievements/delete/<int:achievement_id>/', views.delete_achievement, name='delete_achievement'),
    path('donations/', views.donation_list, name='donation_list'),
    path('donations/create/', views.create_donation, name='create_donation'),
    path('donations/edit/<int:donation_id>/', views.edit_donation, name='edit_donation'),
    path('donations/delete/<int:donation_id>/', views.delete_donation, name='delete_donation'),
    path('jobs/', views.view_job, name='view_job'),
    path('jobs/filter/', views.filter_job, name='filter_job'),
    path('jobs/add/', views.add_job, name='add_job'),
    path('jobs/edit/<int:job_id>/', views.edit_job, name='edit_job'),
    path('jobs/delete/<int:job_id>/', views.delete_job, name='delete_job'),
    path("internships/", views.internship_list, name="internship_list"),
    path("internships/create/", views.internship_create, name="internship_create"),
    path("internships/filter/", views.filter_internship, name="filter_internship"),
    path('internship/edit/<int:internship_id>/', views.internship_edit, name='internship_edit'),path('internship/delete/<int:internship_id>/', views.internship_delete, name='internship_delete'),
    path('college/student/register/', views.student_register, name='student_register'),
    path('user/convert_alumni/', views.convert_alumni, name='convert_alumni'),
    path('user/convert_to_alumni/', views.convert_to_alumni, name='convert_to_alumni'),
    path('user/change_password/', views.change_password, name='change_password'),
    path('user/profile_update/', views.update_profile_std, name='update_profile_std'),
    path('user/profile_view/', views.profile_view, name='profile_view'),
    path("user/alumni/update_alumni", views.alumni_update, name = "alumni_update"),
    path('alumni-directory/', views.alumni_directory, name='alumni_directory'),
    path('student-directory/', views.student_directory, name='student_directory'),
    path('alumn/alumni_career_track', views.alumni_career_track, name='alumni_career_track'),
    path('alumn/search_career_track', views.search_career_track, name='search_career_track'),
    path('alumni/career_track/download/', views.download_career_track, name='download_career_track'),
    path('alumni_directory/search/', views.alumni_directory_search, name='alumni_directory_search'),
    path('student_directory/search/', views.student_directory_search, name='student_directory_search'),
    path('departments/', views.department_list, name='department_list'),
    path('departments/add/', views.add_department, name='add_department'),
    path('departments/edit/<int:dept_id>/', views.edit_department, name='edit_department'),
    path('departments/delete/<int:dept_id>/', views.delete_department, name='delete_department'),
    path('change-user-email/', views.change_user_email, name='change_user_email'),

]